### ISSUE TITLE
okhttp版本问题

### ISSUE THREAD

**Issue by Zephery** [TencentCloud/tencentcloud-sdk-java#101]
这个版本的okhttp在macos10.15.6下会报错
javax.net.ssl.SSLHandshakeException: Server chose TLSv1, but that protocol version is not enabled or not supported by the client.
希望解决下

**Comment by Zephery** [comment]
oracle jdk 1.8.251
oracle jdk 14.0.2
open jdk 14.0.2
全部不行

**Comment by Zephery** [comment]
已解决
![image](https://user-images.githubusercontent.com/14806207/92746234-a751af80-f3b5-11ea-9a7b-713801fcd93d.png)

设置tls为兼容模式，官方请考虑一下哈~~

**Comment by Zephery** [comment]
补充一下，主要是cmq-java-sdk这个项目的HttpUtil修改为兼容模式

**Comment by zqfan** [comment]
@Zephery 已反馈给cmq团队，烦请到这里 http://github.com/tencentyun/cmq-java-sdk
