### ISSUE TITLE
缺少账号相关功能

### ISSUE THREAD

**Issue by 0312birdzhang** [TencentCloud/tencentcloud-sdk-java#102]
如获取项目列表 https://cloud.tencent.com/document/product/378/4400

**Comment by zqfan** [comment]
这个是api2.0的接口，请使用api2.0的sdk：github.com/qcloudapi/qcloudapi-sdk-java
这个sdk里面只包含api3.0的接口

**Comment by 0312birdzhang** [comment]
谢谢，解决了 👍
