### ISSUE TITLE
试看时长与配置不匹配问题

### ISSUE THREAD

**Issue by long47964** [TencentCloud/tencentcloud-sdk-java#103]
参考文档：https://cloud.tencent.com/document/product/266/14047

开启了防盗链，配置试看时长，但是实际播放链接时长和设置值不匹配，比如设置了180秒，实际可能是188秒，也可能是183秒，这个问题有处理的方法吗？

**Comment by zqfan** [comment]
请到控制台工单系统反馈给对应的云点播业务。SDK解决不了业务逻辑问题。
