### ISSUE TITLE
SDK 示例调用问题

### ISSUE THREAD

**Issue by Abnori** [TencentCloud/tencentcloud-sdk-java#104]
[TencentCloudSDKException]message:java.net.SocketException-Connection reset requestId

使用的是readme的例子，secret在api explorer可以调用，但是本地抛出了这个异常

各个版本的sdk都一样，应该不是版本问题，想知道为什么会这样？

**Comment by Abnori** [comment]
不只是cvm，vpc的调用也是

**Comment by zqfan** [comment]
检查本地是否有代理，代理工作是否正常

**Comment by Abnori** [comment]
我用winhttp show proxy查看本机代理，显示是没有代理服务器，这应该是没有代理？

**Comment by Abnori** [comment]
设置里也看了，没有代理设置

**Comment by zqfan** [comment]
那只能抓包看看网络报文了。另外可以浏览器直接打开你使用的域名，看浏览器能否正确处理，只要有requestid返回就算正常

**Comment by Abnori** [comment]
我用公司网络测了 域名，确实是没有返回response，应该是公司网络配置的问题，谢谢回复了！
