### ISSUE TITLE
关于Filter

### ISSUE THREAD

**Issue by Abnori** [TencentCloud/tencentcloud-sdk-java#105]
在使用多种产品的获取列表接口时，发现公有的filter在不同的产品包中都有对应的类。

编写代码时需要将同一段转filter的代码编写多次，代码重复还是比较让人烦恼的。

请问有考虑过将各种云产品的filter进行整合吗？或者有比较好的实现方式吗？

**Comment by zqfan** [comment]
各个产品的Filter可能定义的有所差异，目前还没有好的办法统一起来
