### ISSUE TITLE
手动上传jar包不可用，如何解决

### ISSUE THREAD

**Issue by maxiao124** [TencentCloud/tencentcloud-sdk-java#108]
公司私服不可连接公网，将该jar手动上传到私服，然后从私服拉取依赖，编译，打包，都没有问题，最后部署服务（部署机器有公网环境）也成功了，但是就是访问API拿不到响应，也不报错，使用API：

DescribeCaptchaResult | 核查验证码票据结果
-- | --

是该jar包需要什么特殊的依赖我没有嘛？？？

**Comment by zqfan** [comment]
打点日志看看。没响应也不报错，看看停在哪一步进行不下去，有没有多线程，是不是死锁没释放（sdk中没锁，也没线程安全，同步调用）
