### ISSUE TITLE
请问请求云函数要怎么用呢?

### ISSUE THREAD

**Issue by siyehua** [TencentCloud/tencentcloud-sdk-java#111]
我的云函数使用的 api 请求触发, 但是不知道要怎么用, 好像没有一个例子是教我怎么调用云函数

**Comment by vnaso** [comment]
https://console.cloud.tencent.com/api/explorer?Product=cvm&Version=2017-03-12&Action=DescribeImportImageOs&SignVersion=

**Comment by siyehua** [comment]
> https://console.cloud.tencent.com/api/explorer?Product=scf&Version=2018-04-16&Action=Invoke&SignVersion=

这个不知道怎么设置, 我想通过类似 postman 这样的工具, 应该怎么请求呢? 比如这种在线请求网站, 不知道要怎么设置参数
https://www.sojson.com/http/test.html

**Comment by vnaso** [comment]
> > https://console.cloud.tencent.com/api/explorer?Product=scf&Version=2018-04-16&Action=Invoke&SignVersion=
> 
> 这个不知道怎么设置, 我想通过类似 postman 这样的工具, 应该怎么请求呢? 比如这种在线请求网站, 不知道要怎么设置参数
> https://www.sojson.com/http/test.html

文档看不懂的话建议直接打客服，手把手教学

**Comment by zqfan** [comment]
此SDK是对腾讯云API的封装，并未包含其他业务逻辑，如果有非直接调用api的逻辑，是需要另外编程的。
如果是调用云函数scf的api，利用api explorer生成sdk代码就可以调用。post man这种工具无法完成请求签名。
如果是在云函数内部调用api，则在你的项目里直接指定sdk作为包依赖，同样用api explorer生成sdk代码放在你的项目里。

**Comment by siyehua** [comment]
> 此SDK是对腾讯云API的封装，并未包含其他业务逻辑，如果有非直接调用api的逻辑，是需要另外编程的。
> 如果是调用云函数scf的api，利用api explorer生成sdk代码就可以调用。post man这种工具无法完成请求签名。
> 如果是在云函数内部调用api，则在你的项目里直接指定sdk作为包依赖，同样用api explorer生成sdk代码放在你的项目里。

我是生成了云函数, 然后触发模式设置成 api 请求, 然后发现直接用 postman 这种工具不知道要怎么构造, 用这个项目的例子好像也没有例子. 请问你说的 api explorer 是什么呢

**Comment by zqfan** [comment]
@siyehua api请求都需要计算签名，签名基本上都需要实时计算，不存在一个签名算好了，然后重复一直使用很久的可能。postman只能直接填请求参数（也许有高级用法可以计算而不是填写吧），而且据我了解云函数中都是代码调用，不能用postman这种工具。如果仅仅是调试，api explorer也能调试，至少在自动完成签名方面比postman要好用很多。https://console.cloud.tencent.com/api/explorer
