### ISSUE TITLE
CVM定期创建磁盘快照功能

### ISSUE THREAD

**Issue by 0312birdzhang** [TencentCloud/tencentcloud-sdk-java#113]
在网页创建新实例的时候可以勾选设置自动创建系统盘数据盘快照，在接口文档和sdk中都没有发现此功能的使用方法，是否接口还未添加支持？

![image](https://user-images.githubusercontent.com/1762041/113234325-a6418a80-92d3-11eb-9e37-58688112061b.png)

**Comment by zqfan** [comment]
控制台可能是多个接口的组合设置，你可以在控制台右上角找一个叫api inspector的工具，查看到底调用了哪些接口。
或者直接提工单给cvm产品咨询吧

**Comment by 0312birdzhang** [comment]
谢谢，已找到 https://console.cloud.tencent.com/api/explorer?Product=cbs&Version=2017-03-12&Action=CreateAutoSnapshotPolicy&SignVersion=
