### ISSUE TITLE
云异常事件JSON转Java实体的Bug

### ISSUE THREAD

**Issue by lshuq** [TencentCloud/tencentcloud-sdk-java#114]
sdk版本：3.1.229(monitor)
DescribeProductEventList方法返回的DescribeProductEventListResponse里边包含了DescribeProductEventListEvents数组
DescribeProductEventListEvents类有个ViewName:String类型。
DescribeProductEventList在获取数据的时候拿到的JSON字符串里面ViewName并不是一个String对象。
在MonitorClient的DescribeProductEventList方法（544行），有以下代码
rsp = (JsonResponseModel)this.gson.fromJson(rspStr, type)
此处会抛出异常，导致无法正常返回结果

**Comment by zqfan** [comment]
收到，我联系下对应的负责人看看，多谢反馈。
