### ISSUE TITLE
okhttp版本问题

### ISSUE THREAD

**Issue by fuzui** [TencentCloud/tencentcloud-sdk-java#116]
想询问下大概什么时候会升级到3，虽然readme中有给出解决方案，但尝试后依然无法解决，我用的openfeign最新的okhttp于此冲突，确实是okio 的问题。是否以后会有解耦http依赖的计划，例如[simple-http](https://github.com/xkcoding/simple-http)这种。

**Comment by zqfan** [comment]
目前暂无升级计划，不过我们会考虑的。

**Comment by fuzui** [comment]
了解了，感谢
