### ISSUE TITLE
版本升级问题

### ISSUE THREAD

**Issue by liaozan** [TencentCloud/tencentcloud-sdk-java#119]
每个sdk能不能单独设置不同的版本，而不是跟着主版本走？
看现有的sdk升级，几乎一周会有一个版本迭代，但是其实并不是每个子模块都有更新，这会不会导致真正需要更新的sdk会因为版本升级太频繁而放弃升级从而导致漏洞存在？

**Comment by zqfan** [comment]
你说的是有道理的，我之前也考虑过。
目前是出于管理方便而统一版本号的，不然上百个产品外加各种语言，即使最新的版本号也会多达上千，提工单的时候容易引起混乱。仅仅目前这种状况，许多人就已经搞不清楚了，唉。
精细化的运营总是要的，只是我们还没搞定对部分用户如何引导，使他们正确使用maven等包管理工具的问题，得等一等了
