### ISSUE TITLE
新版sdk没有单发吗

### ISSUE THREAD

**Issue by GabbyMrH** [TencentCloud/tencentcloud-sdk-java#120]
看到官方文档示例单手机号是集合类型，我测试 了一下是群发，那么请问单发的示例在哪呢?

**Comment by GabbyMrH** [comment]
文档地址:https://cloud.tencent.com/document/product/382/43194

**Comment by zqfan** [comment]
这个是短信产品团队自己提供的文档，如有疑问可以到控制台提工单给短信产品咨询下。
另外，如果手机号是集合类型，那应该也可以只填一个手机号的。
