### ISSUE TITLE
引入的依赖包太大了

### ISSUE THREAD

**Issue by WhiteGreeny** [TencentCloud/tencentcloud-sdk-java#124]
通过maven引入的jar包达到了22M，可否精简一下？

**Comment by zqfan** [comment]
![image](https://user-images.githubusercontent.com/2180987/122329349-da882700-cf63-11eb-8f1b-c780edd3a878.png)

**Comment by zqfan** [comment]
其实22MB对于现在的磁盘来说,算不得太大, 对于下载还有镜像源提供加速,  不知道你的应用是什么场景?

**Comment by WhiteGreeny** [comment]
> 其实22MB对于现在的磁盘来说,算不得太大, 对于下载还有镜像源提供加速, 不知道你的应用是什么场景?

小团队，资源有限
