### ISSUE TITLE
即时通讯（IM）相关的接口什么时候能够集成进来

### ISSUE THREAD

**Issue by Kuidaxia** [TencentCloud/tencentcloud-sdk-java#134]
即时通讯（IM）相关的接口什么时候能够集成进来，原本的方式还得自己编码、加密、自己写http请求相关的代码，说实话，挺难用的。

**Comment by zqfan** [comment]
请到控制台工单系统提单，向即时通讯产品咨询何时在官网发布API3.0接口。只要该产品在官网发布了API接口文档，SDK当天就会发布版本支持。
