### ISSUE TITLE
TC3-HMAC-SHA256 支持了吗？

### ISSUE THREAD

**Issue by mikewin** [TencentCloud/tencentcloud-sdk-java#14]
上传文件（base64之后）大小为15MB，上传失败，返回的消息说需要 TC3-HMAC-SHA256 签名
目前SDK支持这种签名了么？ 
设置签名方法为TC3-HMAC-SHA256，报告
TencentCloudSDKException]message:Algorithm TC3-HMAC-SHA256 not available

**Comment by zqfan** [comment]
现已支持（35213f0662a34bdc08ae630886d81c84f70c4948），待发布版本
