### ISSUE TITLE
为什么同样的参数和请求类型但是不同工具不一样

### ISSUE THREAD

**Issue by EndOfMaster** [TencentCloud/tencentcloud-sdk-java#142]
我只是用其中一部分功能，不想引用整个sdk，就自己拆解你们sdk写了一下，但是我发现同样的参数和请求类型，用okclient请求可以通，但是用的我本来的httpclient就不行

我是接入的tbp聊天服务

**Comment by zqfan** [comment]
可以按产品引用的：
引用方法可参考示例。
<dependency>
    <groupId>com.tencentcloudapi</groupId>
    <artifactId>tencentcloud-sdk-java</artifactId>
    
    
    <version>3.1.316</version>
</dependency>
如上引用方式会将腾讯云所有产品sdk下载到本地，可以将artifactId换成tencentcloud-sdk-java-cvm/cbs/vpc等，即可引用特定产品的sdk，代码中使用方式和大包相同，可参考示例。最新版本也可在Maven仓库查询，可大大节省存储空间。

自己实现没别的窍门，按照签名方法实现就好了，官方文档有java代码签名示例，注意发送的时候必须和计算签名的时候内容一致。
