### ISSUE TITLE
[TencentCloudSDKException]message:java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 220  requestId:

### ISSUE THREAD

**Issue by somebody88** [TencentCloud/tencentcloud-sdk-java#15]
IotClient 类的AddDevice(AddDeviceRequest req) 方法第83行：rsp  = gson.fromJson(this.internalRequest(req, "AddDevice"), type); 在(this.internalRequest(req, "AddDevice")已经正常返回结果的情况下报：
[TencentCloudSDKException]message:java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 220  requestId:
	at com.tencentcloudapi.iot.v20180123.IotClient.AddDevice(IotClient.java:85)

**Comment by zqfan** [comment]
@somebody88 使用的sdk版本是多少？能否升级到最新的版本再试一下？这个问题是因为SDK中认为某个字段应该是一个对象，但实际上返回的是字符串，最新的API文档上显示，字段应该都是字符串，所以有可能是你的sdk版本不是最新的导致的。https://cloud.tencent.com/document/product/568/16469#Device

**Comment by somebody88** [comment]
本来用的readme里的3.0.1，现在把版本升级到了3.0.35问题解决了，感谢！一个建议README同步更新一下^_^
