### ISSUE TITLE
设置了镜像仓库都下不下来

### ISSUE THREAD

**Issue by L-GROSS** [TencentCloud/tencentcloud-sdk-java#153]
![12d46eb5711f03021455f0d8f5ee0f3](https://user-images.githubusercontent.com/42738826/143973452-f8ce59cb-b0c5-4bab-b856-035929ceadcc.png)

**Comment by luffykou** [comment]
implementation 'com.tencentcloudapi:tencentcloud-sdk-java:3.1.434'

这都sync in progress……一天了，什么时候是个头啊

**Comment by zqfan** [comment]
参考readme，设置腾讯云镜像源就可以了
![image](https://user-images.githubusercontent.com/2180987/149790202-2d7683fd-0998-441d-89b1-4674ff77ed71.png)
