### ISSUE TITLE
可以升级下Gson版本吗

### ISSUE THREAD

**Issue by FantaZZ** [TencentCloud/tencentcloud-sdk-java#158]

**Comment by zqfan** [comment]
请问具体原因是什么呢？

**Comment by FantaZZ** [comment]
@zqfan  在spring-boot 2.6.4中，不兼容低版本的 2.2.4 gson。
即使spring中兼容，gson 2.2.4 是2013年发布的，gson 已经更新到2.9了，中间修复了很多问题。

**Comment by FantaZZ** [comment]
@zqfan  在spring-boot 2.6.4中，不兼容低版本的 2.2.4 gson。
即使spring中兼容，gson 2.2.4 是2013年发布的，gson 已经更新到2.9了，中间修复了很多问题。

**Comment by zqfan** [comment]
好的，我看下gson官方的release说明，如果不影响到兼容的话，会适当升级到较新的版本
