### ISSUE TITLE
关于部署到weblogic12c中间件项目使用SDK的问题踩坑反馈

### ISSUE THREAD

**Issue by xzqqqcom** [TencentCloud/tencentcloud-sdk-java#161]
公司最近对接了很多腾讯云的服务，由于部分项目老旧，SSM部署在weblogic12c应用容器里运行的，引入了tencentcloud-sdk-java就无法识别项目，直接报错，出于经验第一反应就是jar包冲突，来回折腾了半天，由于该jar包过于底层weblogic12c提示的错误根本无从下手（提示信息：无法识别应用程序，IOException.....），于是我换了一种思路找到腾讯云sdk的pom依赖，对里面的依赖挨个试了一遍，终于找到了它**javax.xml.bind**，没错就是它惹的祸。
既然找到了那么大家很自然就想到weblogic.xml加`<wls:package-name>javax.xml.bind</wls:package-name>`，如果你加它还是无法解决的，刚才前面提到这个jar依赖对weblogic来说过于底层，这种方法也一样报错，我是直接项目pom文件里打包做了排除才成功的，分享给大家：
`        <dependency>`
`           <groupId>javax.xml.bind</groupId>`
`            <artifactId>jaxb-api</artifactId>`
`            <version>2.3.0</version>`
`            <scope>provided</scope>`
`        </dependency>`

不过还是建议官方看看如何调整一下依赖，这玩意儿应该所有应用容器中间件都有。

PS：还有的方案是将依赖版本替换掉weblogic的底层jar包后重启weblogic-adminserver，个人不推荐此方案可能会影响weblogic的正常运行。

**Comment by zqfan** [comment]
请问你们环境的jdk是多少？
引入xml bind包是因为这个issue：https://github.com/TencentCloud/tencentcloud-sdk-java/issues/6
provide并不能适用于我们所有的用户
我想想可不可以直接移除掉整个xml bind依赖，用标准库的方法手工实现下逻辑

**Comment by zqfan** [comment]
可能的备选：https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html

**Comment by xzqqqcom** [comment]
> 请问你们环境的jdk是多少？ 引入xml bind包是因为这个issue：#6 provide并不能适用于我们所有的用户 我想想可不可以直接移除掉整个xml bind依赖，用标准库的方法手工实现下逻辑

老铁，用的JDK1.7_80

**Comment by xzqqqcom** [comment]
> 请问你们环境的jdk是多少？ 引入xml bind包是因为这个issue：#6 provide并不能适用于我们所有的用户 我想想可不可以直接移除掉整个xml bind依赖，用标准库的方法手工实现下逻辑

项目用1.8也能跑，只不过生产1.7不能动现在，也常识过1.8去部署一样的错，应该是weblogic的依赖问题

**Comment by xzqqqcom** [comment]
> 请问你们环境的jdk是多少？ 引入xml bind包是因为这个issue：#6 provide并不能适用于我们所有的用户 我想想可不可以直接移除掉整个xml bind依赖，用标准库的方法手工实现下逻辑

我刚才看了，因为有人用JDK9才开始引入的这个依赖，要不把SDK，按jdk版本分一分
