### ISSUE TITLE
SDK代理访问Endpoint耦合的问题

### ISSUE THREAD

**Issue by huxipi** [TencentCloud/tencentcloud-sdk-java#162]
先说说遇到的问题:
我们用SDK开发应用程序后在应用区域部署,由于有多台服务,为安全起见在应用区部署Proxy服务器(nginx)统一出口,然后通过这台服务器代理发送到DMZ正向代理服务器(nginx2),然后通过正向代理发送到目标云服务主机.
服务->应用区统一代理(n1)->DMZ外联正向代理->腾讯云主机
但是,修改地址发现访问不了,SDK对Endpoint耦合度太高,想通过请求PATH也需修改源码,也怕将来官方版本更新....
设置代理IP端口为应用区统一代理(n1),请求代理直接访问目标云主机,自然也访问不了.
相信这个问题还是比较普遍的,能否通过服务名而不是Endpoint来处理访问路径呢?

**Comment by zqfan** [comment]
SDK支持设置代理的，https://github.com/TencentCloud/tencentcloud-sdk-java#%E4%BB%A3%E7%90%86
但是多跳的场景我并没有测试过，
你说的服务名指的是代理的用户名吗？SDK也是支持设置的，但是需要同时设置代理的密码。
SDK对腾讯云服务endpoint是直接依赖的，否则api无法正常发起

**Comment by huxipi** [comment]
> SDK支持设置代理的，https://github.com/TencentCloud/tencentcloud-sdk-java#%E4%BB%A3%E7%90%86 但是多跳的场景我并没有测试过， 你说的服务名指的是代理的用户名吗？SDK也是支持设置的，但是需要同时设置代理的密码。 SDK对腾讯云服务endpoint是直接依赖的，否则api无法正常发起

 谢谢,我知道SDK是支持代理的,但我遭遇的场景需要应用区统一出口,因此需要两次转发,也就只能将SDK目标地址设置为应用区出口NGINX,再配置转发到DMZ区域NGINX,最后代理到腾讯云服务器,你说的直接依赖我不太理解,需要解决域名地址与SDK解耦

**Comment by zqfan** [comment]
endpoint会参与到请求的签名计算过程，你可以试试能否直接配hosts，endpoint照旧用腾讯云的域名，但是ip指向你们nginx

**Comment by huxipi** [comment]
> endpoint会参与到请求的签名计算过程，你可以试试能否直接配hosts，endpoint照旧用腾讯云的域名，但是ip指向你们nginx

谢谢,是的我也有看到代码耦合.hosts这种方案也考虑过,但是应用区全部统一出口,其他应用通过PATH实现转发,只能在加PATH来区分应用了,另外这种方式,发送到统一出口端口是443端口吗?
