### ISSUE TITLE
okhttp 版本冲突，麻烦升级一下版本

### ISSUE THREAD

**Issue by hjjoe1213123** [TencentCloud/tencentcloud-sdk-java#164]
Okhttp3 java.lang.NoSuchFieldError: Companion

https://blog.csdn.net/qq_24378737/article/details/124448099

**Comment by plumage** [comment]
+1

**Comment by cf** [comment]
+1

**Comment by ahaha-vip** [comment]
+1

**Comment by zqfan** [comment]
已升级

**Comment by rabbitlhf** [comment]
> 已升级

最早基于哪个版本升级？

**Comment by zqfan** [comment]
> > 已升级
> 
> 最早基于哪个版本升级？

从okhttp 2.7.5升级到okhttp3 3.12.13
