### ISSUE TITLE
JAVA云端录制音频设置布局

### ISSUE THREAD

**Issue by baker-yuan** [TencentCloud/tencentcloud-sdk-java#167]
JAVA代码实现云端录制与回放为啥还要设置设置布局，布局不是视频才需要设置的吗，不设置接口报错
`
@Test
public void contextLoads() {
    try {
        long sdkappid = ;
        String RoomId = "";
        String userId = "";
        String key = "";
        TLSSigAPIv2 tlsSigAPIv2 = new TLSSigAPIv2(sdkappid, key);

        Credential cred = new Credential("", "");
        TrtcClient trtcClient = new TrtcClient(cred, "ap-shanghai");
        CreateCloudRecordingRequest request = new CreateCloudRecordingRequest();

        // TRTC的RoomId，录制的TRTC房间所对应的RoomId。
        request.setRoomId(RoomId);

        // 录制机器人用于进入TRTC房间拉流的UserId，注意这个UserId不能与其他TRTC功能或者录制服务等已经使用的UserId重复，建议可以把房间ID作为userId的标识的一部分。
        request.setUserId(userId);

        // 录制机器人用于进入TRTC房间拉流的用户签名，当前 UserId 对应的验证签名，相当于登录密码，具体计算方法请参考TRTC计算UserSig的方案。
        String userSig = tlsSigAPIv2.genUserSig(userId, 604800);
        request.setUserSig(userSig);

        // TRTC的SdkAppId，和录制的房间所对应的SdkAppId相同。
        request.setSdkAppId(sdkappid);

        // TRTC房间号的类型，必须和录制的房间所对应的RoomId类型相同:
        // 0: 字符串类型的RoomId
        // 1: 32位整型的RoomId（默认）
        request.setRoomIdType(1L);

        System.out.println("userSig=\n" + userSig);

        // 云端录制文件上传到云存储的参数(目前只支持使用腾讯云点播作为存储)。
        StorageParams storageParams = new StorageParams();
        CloudVod cloudVod = new CloudVod();
        TencentVod tencentVod = new TencentVod();
        tencentVod.setExpireTime(0L);
        cloudVod.setTencentVod(tencentVod);
        storageParams.setCloudVod(cloudVod);
        request.setStorageParams(storageParams);

        // 云端录制控制参数
        RecordParams recordParams = new RecordParams();
        // 录制模式：
        // 1：单流录制，分别录制房间的订阅UserId的音频和视频，将录制文件上传至云存储；
        // 2：混流录制，将房间内订阅UserId的音视频混录成一个音视频文件，将录制文件上传至云存储；
        recordParams.setRecordMode(2L); //
        // 房间内持续没有主播的状态超过MaxIdleTime的时长，自动停止录制，单位：秒。默认值为 30 秒，该值需大于等于 5秒，且小于等于 86400秒(24小时)。
        recordParams.setMaxIdleTime(10*60L);
        // 录制的媒体流类型：
        // 0：录制音频+视频流（默认）;
        // 1：仅录制音频流；
        // 2：仅录制视频流，
        recordParams.setStreamType(1L);
        request.setRecordParams(recordParams);

        // 录制音频转码参数
        MixTranscodeParams mixTranscodeParams = new MixTranscodeParams();
        AudioParams audioParams = new AudioParams();
        // 音频采样率:
        // 1：48000Hz（默认）;
        // 2：44100Hz
        // 3：16000Hz。
        audioParams.setSampleRate(1L);
        // 声道数:
        // 1：单声道;
        // 2：双声道（默认）。
        audioParams.setChannel(2L);
        // 音频码率: 取值范围[32000, 128000] ，单位bps，默认64000bps。
        audioParams.setBitRate(32000L);
        mixTranscodeParams.setAudioParams(audioParams);
        request.setMixTranscodeParams(mixTranscodeParams);

        // OutputParams outputParams = new OutputParams();
        // outputParams.setRecordAudioOnly();

        // todo bug音频还要设置布局
        MixLayoutParams mixLayoutParams = new MixLayoutParams();
        mixLayoutParams.setMixLayoutMode(1L);
        request.setMixLayoutParams(mixLayoutParams);

        CreateCloudRecordingResponse response = trtcClient.CreateCloudRecording(request);
        System.out.println(DescribeInstancesResponse.toJsonString(response));
        TimeUnit.SECONDS.sleep(30);
        //contextClose(response.getTaskId(), sdkappid);
        System.out.println();
    } catch (TencentCloudSDKException | InterruptedException e) {
        System.err.println(e.toString());
    }
}
`

**Comment by zqfan** [comment]
SDK只是对接口的封装，业务逻辑是trtc产品侧决定的，需要到官网控制台工单系统提单给trtc反馈解决哈
