### ISSUE TITLE
能把这个包优化一下吗？

### ISSUE THREAD

**Issue by lettgers** [TencentCloud/tencentcloud-sdk-java#172]
整个包大小差不多30M大小

**Comment by sesky4** [comment]
可以使用单独的产品，比如你只使用到了 cvm 产品，只引入 tencentcloud-sdk-java-cvm 即可
> 如上引用方式会将腾讯云所有产品sdk下载到本地，可以将artifactId换成tencentcloud-sdk-java-cvm/cbs/vpc等，即可引用特定产品的sdk，代码中使用方式和大包相同，可参考示例。最新版本也可在[Maven仓库](https://search.maven.org/search?q=tencentcloud-sdk-java)查询，可大大节省存储空间。
