### ISSUE TITLE
如何获取磁盘监控数据

### ISSUE THREAD

**Issue by fit2cloud** [TencentCloud/tencentcloud-sdk-java#19]
GetMonitorDataRequest类里有定义：
@SerializedName("Instances")
@Expose
private Instance[] Instances;

在 api 里：
dimensions.0.name=diskId
dimensions.0.value为块存储ID

最新的 java sdk 里获取监控数据的请求类是否还不支持除了云服务器外的其他监控？

**Comment by zqfan** [comment]
从文档上目前只支持两种，云服务器和cdb，云监控API3.0目前支持的请参考https://cloud.tencent.com/document/api/248/30384

**Comment by zqfan** [comment]
云监控目前已经扩充了一批文档：https://cloud.tencent.com/document/api/248/30384
如果仍不满足，请到控制台工单系统给云监控提单，SDK无法解决这些问题，多谢理解
