### ISSUE TITLE
参数缺失  文本生成图片的请求实体类   com.tencentcloudapi.aiart.v20221229.models.TextToImageRequest

### ISSUE THREAD

**Issue by xiongjunbao** [TencentCloud/tencentcloud-sdk-java#192]
![image](https://github.com/TencentCloud/tencentcloud-sdk-java/assets/46064843/44834760-6d43-4ca8-8466-3c824974722f)

哪一个版本有这个参数嘛  我试了很多版本都没有

**Comment by zqfan** [comment]
用最近发布的3.1.853版本试试。这个很早就有了，稍微新点的版本应该都是有这个方法的。

**Comment by TandK8600** [comment]
> 3.1.853

这个版本还是有这种情况

<img width="956" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-java/assets/64523060/f16d9ae5-44af-4d95-9620-eb6236be6765">
