### ISSUE TITLE
sdk无法调用，影响产品使用

### ISSUE THREAD

**Issue by TandK8600** [TencentCloud/tencentcloud-sdk-java#196]
[AiartClient.java
](https://github.com/TencentCloud/tencentcloud-sdk-java/blob/master/src/main/java/com/tencentcloudapi/aiart/v20221229/AiartClient.java) 81行，如下：

<img width="1034" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-java/assets/64523060/8e6a3913-4976-4672-acb1-b5c89b838e6f">

代码缺失，报错情况：

<img width="915" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-java/assets/64523060/a749466b-e601-41bb-b3fe-d992a68d7f2c">

这是sdk源码的问题，不明白这种编译错误为什么还能放上线给实际客户使用

**Comment by TandK8600** [comment]
看到https://github.com/TencentCloud/tencentcloud-sdk-java/issues/192也有同样的问题，但是按建议换成3.1.853版本还是报错

<img width="956" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-java/assets/64523060/f16d9ae5-44af-4d95-9620-eb6236be6765">

**Comment by zqfan** [comment]
贴下你的pom文件，依赖部分的截图。
看起来是有指定tencentcloud-sdk-java-aiart这个依赖，看看有没有指定tencentcloud-sdk-java-common且版本低于aiart依赖的，通常可以不用单独指定common
