### ISSUE TITLE
价格接口InquiryPriceRunInstances

### ISSUE THREAD

**Issue by yaaamo** [TencentCloud/tencentcloud-sdk-java#2]
传任何实例规格，均返回 0.25的价格；

**Comment by zqfan** [comment]
验证了下，并不是固定的，能否贴出详细的请求和返回呢

**Comment by yaaamo** [comment]
需要怎么详细，具体参数？

**Comment by yaaamo** [comment]
DescribePrice describePrice = new DescribePrice(credentials);
		String instanceType = "M1.SMALL8";//S1.SMALL1,S2.SMALL1,
		String image ="img-0vbqvzfn";//
		describePrice.get("ap-beijing", "ap-beijing-1", instanceType, image);

**Comment by yaaamo** [comment]
debug了一下，InstanceType没有进行组装POST到服务端，本地InstanceType不传，查询结果是0.25
