### ISSUE TITLE
TencentCloudSDKException 中的 getErrorCode 方法为什么注释掉？

### ISSUE THREAD

**Issue by yu123105** [TencentCloud/tencentcloud-sdk-java#22]
请问 3.0.45 release 版本中 TencentCloudSDKException 中的 getErrorCode 方法为什么注释掉？

**Comment by zqfan** [comment]
因为之前的开发人员写糟了，目前还没有地方设置，所以总是get为空，后续会调整异常的逻辑，使得errorcode能被有效初始化，然后这个方法才会变为可用

**Comment by TallerCui** [comment]
这个什么时候能好？除了这种方法能拿到请求的结果，目前还有其他方法吗？

**Comment by yu123105** [comment]
@TallerCui 可以暂时用TencentCloudSDKException 中的 toString 方法获取错误信息

**Comment by zqfan** [comment]
请求如果成功，接口对应的response中有返回的信息，请求失败，会抛出一个TencentCloudSDKException，用e.toString()获取完整内容

**Comment by zjxpcyc** [comment]
@zqfan `e.toString()` 里面包含完整的 `ErrorCode` 吗？

**Comment by zqfan** [comment]
有的

**Comment by brainliangbian** [comment]
no errorCode，it is really egg hurt
