### ISSUE TITLE
cls的maven好像没有及时更新？

### ISSUE THREAD

**Issue by ceeyeoMV** [TencentCloud/tencentcloud-sdk-java#230]
如图，pom中引用了最新版本的cls maven依赖：
![通过maven引入最新的3.1.1022版本的cls sdk](https://github.com/TencentCloud/tencentcloud-sdk-java/assets/138500283/9d39a203-581d-4c0f-af8b-043977b1eee3)
但是在使用日志检索中的import com.tencentcloudapi.cls.v20201016.models.SearchLogRequest 类时，想要进行多主题检索，设置topics时的时候发现SearchLogRequest没有topics字段，如下图所示：
![设置topics时飘红报错](https://github.com/TencentCloud/tencentcloud-sdk-java/assets/138500283/d18e65d8-a1d5-4ff2-b085-295e643a91c3)
![SearchLogRequest类中没有看到topics字段](https://github.com/TencentCloud/tencentcloud-sdk-java/assets/138500283/a8071347-73ab-416e-b4a2-ceed2db6dd28)

然后又去gitee上看了下，发现最新的版本中SearchLogRequest类是有topics字段的，如下图所示：
![gitee上的SearchLogRequest类有topics字段](https://github.com/TencentCloud/tencentcloud-sdk-java/assets/138500283/763d82fd-a56a-424c-99f5-80eb64576398)

所以是不是maven仓库没有及时更新呢？

**Comment by zqfan** [comment]
https://repo1.maven.org/maven2/com/tencentcloudapi/tencentcloud-sdk-java-cls/3.1.1022/

**Comment by ceeyeoMV** [comment]
> https://repo1.maven.org/maven2/com/tencentcloudapi/tencentcloud-sdk-java-cls/3.1.1022/ 从这里下载到的包来看，里面是有对应字段的，可以看下本地maven是否有更新成功到对应的版本

嗯嗯是的，更新了有的，多谢
