### ISSUE TITLE
参数名称请小写

### ISSUE THREAD

**Issue by hwy1782** [TencentCloud/tencentcloud-sdk-java#24]
https://github.com/TencentCloud/tencentcloud-sdk-java/blob/master/src/main/java/com/tencentcloudapi/aai/v20180522/models/ChatRequest.java

java 中参数名称请小写开头

**Comment by zqfan** [comment]
的确不符合编程规范，这是因为我们无法对接口里的参数做限制，有的接口直接定义参数为Class，然后小写必定报错，大写不会有关键字冲突
