### ISSUE TITLE
java.lang.Error: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found

### ISSUE THREAD

**Issue by wangsuicheng** [TencentCloud/tencentcloud-sdk-java#26]
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl" on path: DexPathList

我用的是：
implementation 'com.tencentcloudapi:tencentcloud-sdk-java:3.0.31' 这个版本，还需要加什么依赖吗？

**Comment by wangsuicheng** [comment]
implementation 'javax.xml.bind:jaxb-api:2.3.0'
implementation 'javax.xml:jaxp-api:1.4.2'
奇怪，我引入这两个依赖还是报错呀，我是1.8的java

**Comment by zqfan** [comment]
这个sdk不支持移动端（android）环境，至少一开始没这个打算，也未测试过兼容性。

**Comment by wangsuicheng** [comment]
> 这个sdk不支持移动端（android）环境，至少一开始没这个打算，也未测试过兼容性。

噢，那有支持语音测评的android sdk了吗？还是说目前只能通过api来调用？

**Comment by zqfan** [comment]
有的，他们自己实现了移动端的（ios和android）：https://github.com/TencentCloud/tencentcloud-sdk-android-soe

**Comment by fantouch** [comment]
根据Android 官方文档 https://developer.android.com/reference/javax/xml/datatype/DatatypeFactory.html#newInstance%28%29 其中有说明 Note that you must supply your own implementation (such as Xerces); Android does not ship with a default implementation.

所以解决办法是添加依赖   implementation group: 'xerces', name: 'xercesImpl', version: '2.11.0'

**Comment by HS-Gray** [comment]
> 根据Android 官方文档 https://developer.android.com/reference/javax/xml/datatype/DatatypeFactory.html#newInstance%28%29 其中有说明 Note that you must supply your own implementation (such as Xerces); Android does not ship with a default implementation.
> 
> 所以解决办法是添加依赖 ` implementation group: 'xerces', name: 'xercesImpl', version: '2.11.0'`

2.11.0的版本的依赖可能还是不会生效，可以换一下2.12.0的版本试试
implementation group: 'xerces', name: 'xercesImpl', version: '2.12.0'

**Comment by stustatic** [comment]
> > 根据Android 官方文档 https://developer.android.com/reference/javax/xml/datatype/DatatypeFactory.html#newInstance%28%29 其中有说明 Note that you must supply your own implementation (such as Xerces); Android does not ship with a default implementation.
> > 所以解决办法是添加依赖 ` implementation group: 'xerces', name: 'xercesImpl', version: '2.11.0'`
> 
> 2.11.0的版本的依赖可能还是不会生效，可以换一下2.12.0的版本试试 implementation group: 'xerces', name: 'xercesImpl', version: '2.12.0'

android端人脸变换如下使用不会报错：
implementation 'com.tencentcloudapi:tencentcloud-sdk-java:3.1.536'
implementation group: 'xerces', name: 'xercesImpl', version: '2.12.0'
