### ISSUE TITLE
timestamp数组类型错误

### ISSUE THREAD

**Issue by cool6p** [TencentCloud/tencentcloud-sdk-java#27]
![image](https://user-images.githubusercontent.com/28177505/52108852-62d92c00-2636-11e9-95e5-009c9c1a2283.png)
这个类里面的timestamp数组类型不应该是float 应该是int才对 否则返回来的数据会有精度问题

**Comment by zqfan** [comment]
感谢反馈问题。sdk是根据官网api文档生成的，这个应该是monitor没有定义好导致的，先看看monitor愿不愿意修正API的定义，如果他们不愿意改，再考虑sdk自己特殊处理

**Comment by cool6p** [comment]
新年快乐 已改了一下源码 辛苦年后尽快同步升级 

发自我的 iPhone

**Comment by zqfan** [comment]
下一个版本将会调整为Long类型

**Comment by cool6p** [comment]
感谢 预计上线时间是？

发自我的 iPhone

**Comment by zqfan** [comment]
3.0.50

**Comment by cool6p** [comment]
谢谢

发自我的 iPhone

**Comment by zqfan** [comment]
此问题先关闭，如果复现了可以重新打开
