### ISSUE TITLE
NPE问题，LogServer中出现空指针问题

### ISSUE THREAD

**Issue by hewjinxu** [TencentCloud/tencentcloud-sdk-java#28]
# main(2)
java.lang.NullPointerException
Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
解析原始
1 com.tencent.qcloud.logutils.LogServer.onActivityStarted(LogServer.java:58)
2 android.app.Application.dispatchActivityStarted(Application.java:211)
3 android.app.Activity.onStart(Activity.java:1252)
4 android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:614)
5 android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
6 android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1337)
7 android.app.Activity.performStart(Activity.java:7080)
8 android.app.Activity.performRestart(Activity.java:7155)
9 android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4161)
10 android.app.ActivityThread.-wrap29(Unknown Source)
11 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
12 android.os.Handler.dispatchMessage(Handler.java:106)
13 android.os.Looper.loop(Looper.java:164)
14 android.app.ActivityThread.main(ActivityThread.java:6530)
15 java.lang.reflect.Method.invoke(Native Method)
16 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:444)
17 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:812)

**Comment by zqfan** [comment]
看堆栈有两个问题，1）此sdk不支持android运行环境，2）logserver看起来是和sdk不相关的代码，我也不确定为何会报这个错误，麻烦具体定位下是否是由sdk引起的

**Comment by hewjinxu** [comment]
我贴错位置了，这个是Android sdk的问题，我在那边重新提单了，此单关闭
