### ISSUE TITLE
DescribeDeviceResponse 中ConnIP问题

### ISSUE THREAD

**Issue by kukuxiahuni** [TencentCloud/tencentcloud-sdk-java#29]
版本：3.0.57
接口：查询设备详情，iotCloud.DescribeDevice(request);
错误： .common.exception.TencentCloudSDKException: java.lang.NumberFormatException:Expected an int but was 2531608329 at line 1 column 1399 path $.Response.ConnIP
原因：问题是 ConnIP的数值超过了 Integer.MAX_VALUE

**Comment by zqfan** [comment]
3.0.59 版本已修复，https://github.com/TencentCloud/tencentcloud-sdk-java/commit/798b6720f6d960003c898995bde847b57c68b402
