### ISSUE TITLE
双螺旋是否支持添加快照盘

### ISSUE THREAD

**Issue by applesline** [TencentCloud/tencentcloud-sdk-java#32]
sdk是否支持双螺旋添加快照盘，大概看了一下源码暂时么有找到双螺旋模块，目前版本（qcloud-java-sdk:2.0.6）是否支持？

**Comment by zqfan** [comment]
SDK中的接口和官网同步，目前官网尚未发布接口文档，因此SDK中不会包含。qcloud-java-sdk这个也是同理，不过qcloud-java-sdk:2.0.7版本支持动态模块及接口调用，你可以咨询下双螺旋的产品如果API2.0是否有接口可调用
