### ISSUE TITLE
永远的3.0.1

### ISSUE THREAD

**Issue by hujh** [TencentCloud/tencentcloud-sdk-java#34]
<dependency>
	<groupId>com.tencentcloudapi</groupId>
	<artifactId>tencentcloud-sdk-java</artifactId>
	<version>3.0.1</version>
</dependency>

建议README 这里稍微更新一下版本吧 或者标注一个 {version} 也好吧

**Comment by zqfan** [comment]
![image](https://user-images.githubusercontent.com/2180987/57431420-57188980-7265-11e9-9001-cf89e09520f3.png)
