### ISSUE TITLE
什么时候升级okhttp为3呢, 现在大多用3, 好多东东不能共用

### ISSUE THREAD

**Issue by cifaz** [TencentCloud/tencentcloud-sdk-java#41]

**Comment by zqfan** [comment]
目前无此计划，有什么特性是你们需要的呢，目前看来，我们仅仅使用了基本的功能而已，似乎没有必要去升级

**Comment by cifaz** [comment]
不是有什么特性, 而是目前公司使用的组件是OKHTTP3, 和你们的冲突, 非要使用只要单独拆出一个工程来, 没办法和基础服务放在一起使用!

**Comment by zqfan** [comment]
依赖不同的jar包怎么会冲突呢？

**Comment by gradlexyz** [comment]
强烈支持迁移到okhttp3
可以与项目无缝切换，不用重新导包，不用改api

**Comment by cifaz** [comment]
亲们, 升级吧, JAR包肯定会冲突呀, JAR只能导一个包, 会自动屏蔽其它的,  实在不能忍, 我们项目现在有2个HTTP工具类, 一个使用apache, 就是因为你们的JAR冲突, 不能使用OKHTTP的工具类

**Comment by liubao425** [comment]
强烈建议升级okhttp3，springcloud2.1.1 版本的okhttp3 都3.6.0了，fegin会冲突，会报错

**Comment by vmwell** [comment]
强烈建议升级okhttp3

**Comment by baklpc** [comment]
> 目前无此计划，有什么特性是你们需要的呢，目前看来，我们仅仅使用了基本的功能而已，似乎没有必要去升级

你能不能去试试你们别的项目组的sdk，一个2.X 一个3.X，你起来个毛线，依赖的okio版本有问题好么，就这还在这回复。。。。

**Comment by woshiawei** [comment]
> > 目前无此计划，有什么特性是你们需要的呢，目前看来，我们仅仅使用了基本的功能而已，似乎没有必要去升级
> 
> 你能不能去试试你们别的项目组的sdk，一个2.X 一个3.X，你起来个毛线，依赖的okio版本有问题好么，就这还在这回复。。。。

这不知道是个什么水平

**Comment by sanyecao2314** [comment]
> 目前无此计划，有什么特性是你们需要的呢，目前看来，我们仅仅使用了基本的功能而已，似乎没有必要去升级

腾讯cmq的sdk已经升级依赖okhttp3了.而okhttp3和2的maven坐标不同.这会导致工程导入两个不同版本的okhttp的jar包!

**Comment by zqfan** [comment]
解决办法参考：https://github.com/TencentCloud/tencentcloud-sdk-java#%E4%BE%9D%E8%B5%96%E5%86%B2%E7%AA%81

**Comment by hongliming** [comment]
![4901108cfa6cbadfa1959fdc21878d2](https://user-images.githubusercontent.com/2437125/128597933-ca89ae51-8411-4167-b9c7-860aecc917b6.png)
