### ISSUE TITLE
关于当前sdk

### ISSUE THREAD

**Issue by forfuns** [TencentCloud/tencentcloud-sdk-java#42]
我们公司有使用腾讯的VOD服务，但是当前这个repo太大了，我们只需要VOD的SDK，但不得不引入整个sdk包，否则只能自己单独删减打包，后续能否单独拆分？

另外，我们也使用“云通讯”服务，可是苦于没找到对应的SDK，我们自己按照自己的需求开发了一部分功能，我们的的TIM SDK（后来在当前repo下发现了一个叫cim。。）全称"[TIMJava](https://github.com/forfuns/TIMJava)"由于项目需求和人手不足，只开发了三个功能模块，希望后续可以继续维护，也希望可以得到一些官方的支持。

并且云通讯的社区貌似并不活跃，这个不应该是腾讯开放平台最有能力和最核心的服务吗，但是总觉得一些不足，比如后台不能可视化管理用户以及聊天和关系信息等等，希望可以加强这一服务

**Comment by zqfan** [comment]
目前暂时不会拆开独立。
cim就是云通信，但是目前只有一个接口，据说只是拿来获取sdk appid。此SDK是用于调用腾讯云API3.0的接口的，其他的产品的sdk是不适合放在这个项目中的。
我会把你的反馈发给云通讯的负责人看，但老实说通常没什么用，别人不会鸟我。最好您到控制台工单系统给云通信提单，这样容易受到重视。
