### ISSUE TITLE
VodClient怎么上传视频呢, 方法找完了都没找到

### ISSUE THREAD

**Issue by cifaz** [TencentCloud/tencentcloud-sdk-java#43]
VodClient怎么上传视频呢, 方法找完了都没找到

**Comment by zqfan** [comment]
此SDK只是对官网公布的接口的封装，并不提供接口如何组合调用的指引。如对云点播产品功能有疑问，请查阅该产品的文档，例如https://cloud.tencent.com/document/product/266/9760 ，或者到控制台工单系统给云点播提工单咨询。
