### ISSUE TITLE
人脸识别里面 URL 如果图片中包含汉字，则报错

### ISSUE THREAD

**Issue by zjxpcyc** [TencentCloud/tencentcloud-sdk-java#44]
应该是一个 BUG ，不知道是你们的，还是用的 request 框架的。

总之，如果把 URL 中的汉字部分给 URLEncode 一下就可以了

**Comment by zqfan** [comment]
请贴一下完整的报错信息

**Comment by zjxpcyc** [comment]
这个 bug 。我通过把 图片 名称部分 urlencode 给规避掉了。完整的报错，好像是 Can't download the image 。 我好像去你们源码里找过这段错误，没有找到。

**Comment by zqfan** [comment]
@zjxpcyc 你是使用哪种签名方式呢？签名v1吗？
“Can't download the image "这个报错是后台返回的，因为url打不开，跟url的格式是有关系的

**Comment by zjxpcyc** [comment]
恩，是 URL 格式的问题。如你们确定不是这个框架问题。就 关了吧。我这边也规避这个错误了

**Comment by zqfan** [comment]
产品可能需要在文档中强调下URL格式，避免使用错误。
