### ISSUE TITLE
调用CreateLiveRecordRule这个方法模板规则已存在返回的Code是InternalError？

### ISSUE THREAD

**Issue by AdolphL** [TencentCloud/tencentcloud-sdk-java#45]
调用CreateLiveRecordRule这个方法，模板规则已存在的情况下为什么返回的Code是InternalError？请检查下，感觉返回InternalError不太友好。

RequestId:b36a1e14-0764-48ac-8f9a-7f9cdbd0d6e0

**Comment by zqfan** [comment]
InternalError代表后台服务出现了异常情况，你可以通过Message查看具体的报错信息。
如果仅仅是入参有问题，一般返回的应该是InvalidParameter之类的才比较合理，不过现在信息比较少，无法判断具体情况。
可以到控制台提工单给云直播咨询或提出需求。SDK只是对调用接口做的封装，无法解释后台逻辑也无法变更后台行为，请谅解。
