### ISSUE TITLE
DetectAuth接口有问题

### ISSUE THREAD

**Issue by li20040314** [TencentCloud/tencentcloud-sdk-java#47]
参数 Name | 否 | String | 姓名。最长长度32位。中文请使用UTF-8编码。

这里使用UTF-8编码，win10环境，tomcat 设置了 URIEncoding="UTF-8"，开发环境设置了 UTF-8，编码时一直，奇数个中文会乱码，偶数个中文不会乱码 ，腾讯对接的几个原厂工程师问了一遍都没有解决，希望这里采用其他方式加密

**Comment by zqfan** [comment]
你可以用API Explorer试试中文的问题，https://console.cloud.tencent.com/api/explorer?Product=faceid&Version=2018-03-01&Action=DetectAuth 
贴出实际的请求和返回让人脸核身的技术支持人员看下吧。
另外可以自己打印（最好是抓包）看看实际发出的请求是否中文不对。
你可以使用TC3-HMAC-SHA256方式POST方法发送，这在新一点的sdk中是默认的选项。你可以试试这种方式能否解决。
