### ISSUE TITLE
各种地方都要用到的Region是String类型，而不是Enum类型

### ISSUE THREAD

**Issue by wsy** [TencentCloud/tencentcloud-sdk-java#5]
应该建立一个enum，来表示各种区域。
比如Region.Guangzhou、Region.Shanghai，而不是让用户去翻文档查到“广州”的Region是“ap-guangzhou”。

**Comment by louishlz** [comment]
多谢建议，我们下个版本支持下

**Comment by zjxpcyc** [comment]
@louishlz 什么时候下个版本 ？

**Comment by zqfan** [comment]
已由此次提交解决https://github.com/TencentCloud/tencentcloud-sdk-java/commit/8ecbdfed4466dafb348928ac7bfb86cc85b02d8b
