### ISSUE TITLE
HTTP headers 应该兼容大小写

### ISSUE THREAD

**Issue by drawdy** [TencentCloud/tencentcloud-sdk-java#56]
问题：
可能是代理的干扰导致接收的 HTTP response header 里都转成小写了（见截图 ），cos sdk 里没有兼容小写情况导致报错
实际上，HTTP headers 是大小写**不**敏感的，参考：https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

![image](https://user-images.githubusercontent.com/16068419/67549614-41c1e980-f737-11e9-9d99-12cd5a0bf839.png)

**Comment by zqfan** [comment]
抱歉，cos有专门的sdk，并不在此项目下。
