### ISSUE TITLE
精确到毫秒的时间戳用Int

### ISSUE THREAD

**Issue by salmonzhg** [TencentCloud/tencentcloud-sdk-java#61]
https://github.com/TencentCloud/tencentcloud-sdk-java/blob/5d64d7bd9f062396a04740eb4ba699033b86b73c/src/main/java/com/tencentcloudapi/iai/v20180301/models/PersonInfo.java#L66

**Comment by zqfan** [comment]
大部分已转为Long，注意会有兼容问题，需要重新编译
