### ISSUE TITLE
部署到tomcat之后，调用TBP平台的TextProcess接口发送的中文内容，在TBP服务器端接收时是乱码

### ISSUE THREAD

**Issue by sunt89** [TencentCloud/tencentcloud-sdk-java#63]
使用SDK调用TextProcess接口，返回回答的内容一直是 “对不起，我不明白你的意思”

查看返回的响应内容，InputText为乱码。
{"DialogStatus":"","BotName":"","IntentName":"","SlotInfoList":[],"InputText":"??????","ResponseMessage":{"GroupList":[{"ContentType":"text/plain","Url":"","Content":"对不起，我不明白你的意思。"}]},"SessionAttributes":"","ResultType":"5","RequestId":"d9c49373-8908-4623-b2e3-9aeb210f87f3"}

直接将SDK代码添加到工程
在doRequestWithTC3方法中，修改sdk代码，获取requestPayload时，设置为utf-8之后乱码问题可以得到解决
requestPayload = AbstractModel.toJsonString(request).getBytes("utf-8");

不清楚这个是不是SDK代码需要修改，还是说Tomcat服务器需要做一些什么额外的配置。

**Comment by zqfan** [comment]
这里用的是默认的字符集，你的jvm启动时指定的可能不是默认的utf8。虽然不知道为什么你的项目需要指定其他字符集，但是sdk中明确的指定字符集有利无害，能够解决你的问题

**Comment by sunt89** [comment]
@zqfan 好的，但是启动jvm的时候没有显式的去指定其他字符集，都是用的默认的配置。

**Comment by sunt89** [comment]
@zqfan   部署的测试环境为 windows 10 以及  windows server 2016，系统原本装的都是英文版本，后来添加的中文语言库。   不清楚和这个有没有什么关联。

**Comment by TrZoey** [comment]
出现了同样的情况，也使用的是默认配置。是否考虑对此处进行更新？

**Comment by zqfan** [comment]
@sunt89 @TrZoey 已经提交https://github.com/TencentCloud/tencentcloud-sdk-java/commit/0ecb7304643cf459c8b58b11ba792d8255c978b9 尝试解决你们遇到的问题，但是我没有简单的途径复现问题，所以也并不确定是否一定能解决你们的问题。最晚在下周四会发布版本包含这个变更，你们也可以提前尝试自行编译jar包测试下，多谢。

**Comment by TrZoey** [comment]
应该可以解决问题。就是win10系统默认编码时GBK导致的。当时修改了jvm启动指令，指定了编码为u8解决了这个问题。

**Comment by zqfan** [comment]
多谢反馈
