### ISSUE TITLE
java.lang.NoClassDefFoundError: com/squareup/okhttp/OkHttpClient

### ISSUE THREAD

**Issue by YouAreALover** [TencentCloud/tencentcloud-sdk-java#70]
初次使用腾讯云短信业务，这个是什么问题 烦请解答 谢谢。

**Comment by zmal** [comment]
okhttp依赖冲突

**Comment by zqfan** [comment]
1、如果你是使用maven管理依赖，则可能是有其他包依赖okhttp并且干掉了sdk依赖的okhttp版本（通常也不太可能，但是可以检查下maven是否已下载sdk依赖的okhttp版本）
2、如果是手动引用，你需要到vendor目录下，把okhttp也加入到你的库引用路径下
