### ISSUE TITLE
地域信息的预设常量类名是什么

### ISSUE THREAD

**Issue by yidasanqian** [TencentCloud/tencentcloud-sdk-java#71]
第二个参数：
example：
https://github.com/TencentCloud/tencentcloud-sdk-java/blob/b96544ba13541e3c769af06c978572f8cf84625d/examples/sms/v20190711/SendSms.java#L59

**Comment by zqfan** [comment]
地域信息目前还没有枚举常量

**Comment by zqfan** [comment]
在这次提交中，我们添加了目前已公开的地域信息，https://github.com/TencentCloud/tencentcloud-sdk-java/commit/8ecbdfed4466dafb348928ac7bfb86cc85b02d8b#diff-967fa90ed8a6874e601c4dcc178ddbfa
