### ISSUE TITLE
tencentcloud-sdk-java  和  腾讯云 cmq http sdk关于okhttp冲突

### ISSUE THREAD

**Issue by shockcao** [TencentCloud/tencentcloud-sdk-java#74]
tencentcloud-sdk-java  和  腾讯云 cmq http sdk关于okhttp冲突
tencentcloud-sdk-java使用okhttp2.5  cmq使用okhttp3.7
okhttp这两个版本的包名不同，引用okio版本也不同，排除任何一个okhttp版本都会导致另一个sdk不可用报错
作为腾讯云的sdk，你们应该保持内部统一，方便用户   以相同标准提供sdk服务，保障用户的可用性

**Comment by zqfan** [comment]
虽说都是腾讯云的，其实还是不同的团队在开发，保持内部统一是比较困难的。okhttp3.7也是相对较低的版本了
okhttp2并不能无缝升级到okhttp3，我们还需要对sdk直接调用okhttp部分修改下才可以，而且okhttp3本身的运行机制有改动，对于sdk简单的调用场景也许没有问题，但我还无法预知对于多线程使用sdk client会有什么影响。
会考虑升级到okhttp3，但是可能不会和其他sdk保持一致

**Comment by zqfan** [comment]
主要是okio版本不同导致的，解决办法参考：https://github.com/TencentCloud/tencentcloud-sdk-java#%E4%BE%9D%E8%B5%96%E5%86%B2%E7%AA%81

虽然官方文档声称说升级没有风险，但是实测发现会大面积报错，毕竟大版本升级不可能不改动。而且牵涉到连接池方面的变更，对于复杂场景的使用，依然担忧。不过鉴于okhttp2.x版本已不再更新，升级okhttp3的事情还是会提上日程。
