### ISSUE TITLE
如何引入到Android项目中

### ISSUE THREAD

**Issue by wangshuohulala** [TencentCloud/tencentcloud-sdk-java#75]
声明；本人小白
还望给予详细解释
我是使用 通过源码包 到本地解压的方式，但是我看vendor文件夹里只有gson okhttp okio，没有看到其他相关的jar包

**Comment by zqfan** [comment]
建议通过依赖的方式引入，vendor目录只有直接的依赖，没有更深层的依赖，根据打包方式不同，仅使用这几个可能会失败。
我们并没有测试过对andriod项目的兼容性，但是理论上是可以的。可以到已关闭的issue https://github.com/TencentCloud/tencentcloud-sdk-java/issues/54  https://github.com/TencentCloud/tencentcloud-sdk-java/issues/26  里找到前人的办法，具体而言就是把android环境缺失的包补上就可以了。
