### ISSUE TITLE
okhttp就是不升级也是服了， 你们家开发都这么牛逼么？你们用2.x,你们别的项目组用3.X，特么一个项目用就抱错，做开放平台能不能用点心？

### ISSUE THREAD

**Issue by baklpc** [TencentCloud/tencentcloud-sdk-java#77]

**Comment by woshiawei** [comment]
确实很不好用 垃圾；。。。。。

**Comment by sanyecao2314** [comment]
我也遇到同样的问题.cmq的sdk使用的okhttp是3.7.然后okhttp3和2的maven坐标有变化.会导致引两个版本的jar包进来.这个能否统一一下

**Comment by baklpc** [comment]
人家牛逼，换阿里云吧，又不是非他家不用

**Comment by zqfan** [comment]
maven依赖出现包冲突并不罕见吧，maven有自己解析依赖的顺序和规则，具体可以参考maven手册。
okhttp和okhttp3本身为了兼容就对坐标隔离了，两个一起引入并不会造成问题，但是这两个包共同依赖okio，okhttp3依赖okio1.12.0，如果maven中依赖顺序不对，会导致okio低版本被maven优先解析，导致okhttp3出现方法找不到等错误。
解决办法，1、明确指定okio版本为1.12.0或以上作为显式依赖
2、调整sdk和cmq sdk的依赖顺序，cmq sdk放在前面，形如
```
    <dependency>
      <groupId>com.qcloud</groupId>
      <artifactId>cmq-http-client</artifactId>
      <version>1.0.7</version>
    </dependency>
    <dependency>
      <groupId>com.tencentcloudapi</groupId>
      <artifactId>tencentcloud-sdk-java</artifactId>
      <version>3.1.59</version>
    </dependency>
```
