### ISSUE TITLE
[TencentCloudSDKException]message:AuthFailure.UnauthorizedOperation-You are not authorized to perform this operation. Check your CAM policies, and ensure that you are using the correct access keys. [[request id:6ecbe97c-fadb-4798-8afa-4e56b9e0f3da]you are not authorized to perform operation (sms:SendSms) resource (*) has no permission

### ISSUE THREAD

**Issue by woshiawei** [TencentCloud/tencentcloud-sdk-java#78]
`[TencentCloudSDKException]message:AuthFailure.UnauthorizedOperation-You are not authorized to perform this operation. Check your CAM policies, and ensure that you are using the correct access keys. [[request id:6ecbe97c-fadb-4798-8afa-4e56b9e0f3da]you are not authorized to perform operation (sms:SendSms)
resource (*) has no permission`

一直包这个异常。这时什么问题？能说明一下吗？

**Comment by zqfan** [comment]
你并未授权执行这个操作。请找你的主帐号在控制台访问管理页面给你授权。
