### ISSUE TITLE
README.md need updating

### ISSUE THREAD

**Issue by yunhenk** [TencentCloud/tencentcloud-sdk-java#8]
Hi, the maven dependency info in README.md is too old. The 3.0.1 version is behind your release, for example it doesn't contain the aai module. Please update it.

**Comment by zqfan** [comment]
Currently we only have a Chinese simplified version of readme, and we noted that: "注意这里的版本号只是举例,您可以在Maven仓库上找到最新的版本。", which means this is just an example, users should find latest version in maven central website.

**Comment by yunhenk** [comment]
sorry, missed that
