### ISSUE TITLE
exmpale 文件夹下面有文档嘛？

### ISSUE THREAD

**Issue by pomestyle** [TencentCloud/tencentcloud-sdk-java#81]
exmpale 文件夹下面有文档嘛？ 那个是哪个？只有代码，没有文档。亲、有文档的话就更好了。

**Comment by zqfan** [comment]
是的，只有代码，有的代码里有注释，有的可能少一点。对示例再专门列文档其实没有太大必要了，我估计也只能啰嗦重复下，还不如直接看源码有用。因为有工具生成sdk调用代码，https://console.cloud.tencent.com/api/explorer ，示例其实没有太大作用了

**Comment by pomestyle** [comment]
我在源码看到了谢谢了。
