### ISSUE TITLE
混贴发票识别

### ISSUE THREAD

**Issue by pomestyle** [TencentCloud/tencentcloud-sdk-java#82]
SDK中混贴发票识别`MixedInvoiceItem`实体类没有`Result`字段 ，返回的json有`Result`字段。

**url**

 https://cloud.tencent.com/document/api/866/37835

**Comment by zqfan** [comment]
麻烦贴一下返回的json。
通常，未在文档中列出（同样的不会在SDK中出现）的字段，可能是处于灰度功能，或业务出于其他原因不愿公开的信息。不建议对这样的字段有太强的依赖。
