### ISSUE TITLE
腾讯专有云环境的证书问题

### ISSUE THREAD

**Issue by songhtdo** [TencentCloud/tencentcloud-sdk-java#84]
你好。
我在腾讯云专有云环境中使用tencentcloud-sdk-java的，出现
javax.net.ssl.SSLHANDshakeException-sum.security.validator.validatorException
我使用工具，将私有云域名的证书下载并放到$JAVA_HOME/jre/lib/security目录中，
重启服务，仍然报同样的错误。
请问在使用tencentcloud-sdk-java时，证书需要特殊设置吗？

**Comment by zqfan** [comment]
如果专有云允许http访问的话，你可以直接https://github.com/TencentCloud/tencentcloud-sdk-java/blob/master/src/main/java/com/tencentcloudapi/common/profile/HttpProfile.java#L127 设置为http访问
如果仅允许https访问，你需要的是导入证书，而不是把证书文件放在某个目录下，参考https://blog.csdn.net/ljskr/article/details/84570573
