### ISSUE TITLE
云点播产品 DescribeDrmDataKey 接口没有封装

### ISSUE THREAD

**Issue by junbaor** [TencentCloud/tencentcloud-sdk-java#94]
文档地址：https://cloud.tencent.com/document/product/266/9643

**Comment by zqfan** [comment]
您好，这是云点播API2.0的接口，这个SDK提供的是API3.0接口的封装。建议您使用此功能对应的API3.0接口，如果不知道具体是哪个，可以到官网控制台提工单到云点播产品咨询。
如果仍需要继续使用API2.0接口，可以考虑使用其对应的SDK：https://github.com/qcloudapi/qcloudapi-sdk-java
